#!/usr/bin/env python3

import yaml
import sys

if (len(sys.argv) != 3):
  print(f'USAGE: {sys.argv[0]} <input>.yaml <output>.tex')
  exit(1)

input_file = sys.argv[1]
outf = open(sys.argv[2], 'w')

data = yaml.load(open(input_file, 'r'), Loader=yaml.Loader)

outf.write(f'''% DO NOT EDIT THIS FILE
% This content is automatically generated from
% {input_file}'

''')

def latex_write(s):
  s = s.replace('&', '\\&')
  outf.write(s)

latex_write('\\begin{description}\n')
for category in data:
  latex_write(f'\\item[{category['category']}]~\n')
  latex_write('  \\begin{itemize}\n')
  for activity in category['activities']:
    latex_write(f'  \\item\n    {activity['name']}: ')
    years = activity['years']
    first = True
    for year in years.keys():
      if not first:
        latex_write(', ')
      else:
        first = False
      latex_write(f'{year}')
    latex_write('.\n')
  latex_write('  \\end{itemize}\n')
latex_write('\\end{description}\n')
